worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;

    sendfile on;

    # —писок серверов, куда будут проксироватьс€ запросы.
    upstream aspnet-app {
        # ћетод балансировки нагрузки по умолчанию (round-robin)
        server app1:5001;
        server app2:5002;

        # ћетод балансировки нагрузки least_conn (наименьшее количество соединений)
        # least_conn;

        # ћетод балансировки нагрузки ip_hash (посто€нное соединение с одного IP)
        # ip_hash;
    }

    upstream rank_calculator {
        # ћетод балансировки нагрузки по умолчанию (round-robin)
        server rank_calculator1:5003;
        server rank_calculator2:5004;
    }

    # 8080 порт - точка входа дл€ пользователей
    server {
        listen 8080;
        server_name localhost;

        location / {
            proxy_pass http://aspnet-app;
        }
    }

    server {
    listen 80;
    server_name localhost;

    location /rank {
        proxy_pass http://rank_calculator;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_cache_bypass $http_upgrade;
    }
}

}